language: python
python:
  - "3.7"

#services:
#    - mysql
#    - someExternalStuff

env:
    global:
     - TRAVIS=true
before_install:
    #   add something to do before install here
install:
    #   actuall install
  - python setup.py install
script:
    #   additional stuff
  - python urlinfo
notifications:
  email:
    recipients:
      - developer1swifty@gmail.com
    on_success: always 
    on_failure: always 